/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers/$workerId'
import { Route as BrowseTaskIdRouteImport } from './routes/browse/$taskId'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseTaskIdRoute = BrowseTaskIdRouteImport.update({
  id: '/browse/$taskId',
  path: '/browse/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/dashboard': typeof DashboardRoute
  '/worker': typeof WorkerRoute
  '/browse/$taskId': typeof BrowseTaskIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/browse': typeof BrowseIndexRoute
  '/workers': typeof WorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/dashboard': typeof DashboardRoute
  '/worker': typeof WorkerRoute
  '/browse/$taskId': typeof BrowseTaskIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/browse': typeof BrowseIndexRoute
  '/workers': typeof WorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/dashboard': typeof DashboardRoute
  '/worker': typeof WorkerRoute
  '/browse/$taskId': typeof BrowseTaskIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/browse/': typeof BrowseIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/dashboard'
    | '/worker'
    | '/browse/$taskId'
    | '/workers/$workerId'
    | '/browse'
    | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/dashboard'
    | '/worker'
    | '/browse/$taskId'
    | '/workers/$workerId'
    | '/browse'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/dashboard'
    | '/worker'
    | '/browse/$taskId'
    | '/workers/$workerId'
    | '/browse/'
    | '/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRoute
  DashboardRoute: typeof DashboardRoute
  WorkerRoute: typeof WorkerRoute
  BrowseTaskIdRoute: typeof BrowseTaskIdRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$taskId': {
      id: '/browse/$taskId'
      path: '/browse/$taskId'
      fullPath: '/browse/$taskId'
      preLoaderRoute: typeof BrowseTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRoute,
  DashboardRoute: DashboardRoute,
  WorkerRoute: WorkerRoute,
  BrowseTaskIdRoute: BrowseTaskIdRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
